### ISSUE TITLE
Supported by which CARLA version?

### ISSUE THREAD

**Issue by eslambakr** [MukhlasAdib/CARLA-2DBBox#4]
Hello,

Thanks for sharing your great efforts, may I ask which version of CARLA your module was built?

**Comment by MukhlasAdib** [comment]
Hi! Thanks for asking. I used CARLA 0.9.8 when I built this module. Do you find anything wrong?

**Comment by eslambakr** [comment]
Thanks for your quick reply.
It will be kind of you if you mention this in the readme.
I am just wondering as CARLA APIs are changing frequently, that's why I am asking.

Thanks,

**Comment by MukhlasAdib** [comment]
You're right, I forgot to mention it. I will update the readme soon. Thanks a lot.
